### ISSUE TITLE
hosting the web app locally. 

### ISSUE THREAD

**Issue by TwilightTechie** [mukundha/real-time-ai-demo#1]
I had the pleasure of attending your talk at the Nutanix Office recently, and I found it quite informative. I'm interested in exploring the project you discussed during the talk, and I would like to host the web app locally. However, I couldn't locate the code for that. Please let me know if the code is yet to be uploaded, or if there's another way for me to access it.

**Comment by mukundha** [comment]
Hey, thanks for checking out, here is the UI for the demo https://github.com/mukundha/movie-recommendations-ui
